### ISSUE TITLE
Is it possible to get class scores for all classes ? 

### ISSUE THREAD

**Issue by dangmanhtruong1995** [westerndigitalcorporation/YOLOv3-in-PyTorch#5]
Hi, Is it possible to get class scores for all classes ? For example we have a dog object. The model predicts that the object is dog, with score 0.9. Is it possible to get scores for other classes, for example: cat - 0.1 ?
I checked many examples but have not found how to get class scores for all classes ?
Thank you very much.

**Comment by wuhy08** [comment]
Because non max suppression requires the category label before the filtering, most NNs with NMS will only give out one label. It is possible to trace back to the raw detection result to find other class scores for the filtered object but requires some work. Since it is not a common feature, the implementation would be left to the field.

**Comment by dangmanhtruong1995** [comment]
Then how do I get the result before NMS ? Tks a lot.
